# Generated by Django 2.0.5 on 2018-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('n', 'new'), ('p', 'processing'), ('pr', 'processed')], max_length=10)),
            ],
        ),
    ]
